'use strict';

// Generic mail nouns that decorate a special-use folder name without changing what
// it means: "Sent Mail", "Gelöschte Elemente", "Отправленные письма". Stripping them
// lets a decorated name fall back to its core word. A name that still has more than
// one meaningful word left after stripping is treated as a user folder and rejected,
// which is what separates "Sent Mail" (a real Sent folder) from "Sent to clients".
// Words that name a special-use folder on their own (like "bin") do not belong here,
// and neither do hyphenated words, since TOKEN_SPLIT below splits on the hyphen and
// no such token could ever be produced.
// Folded by construction so the set matches the form tokens are compared against,
// the same invariant the name tables are tested for.
const GENERIC_TOKENS = new Set(
    [
        // English
        'mail',
        'mails',
        'email',
        'emails',
        'message',
        'messages',
        'item',
        'items',
        'folder',
        'my',
        // German, Dutch, Nordic
        'objekt',
        'objekte',
        'objekten',
        'objekter',
        'elemente',
        'elementen',
        'elementer',
        'nachrichten',
        'berichten',
        'post',
        'poster',
        'viestit',
        'kirjad',
        'meldinger',
        'beskeder',
        // Romance
        'correo',
        'posta',
        'courrier',
        'elementos',
        'elementi',
        'éléments',
        'mensajes',
        'messaggi',
        'mensagens',
        'itens',
        // Slavic
        'poczta',
        'pošta',
        'elementy',
        'wiadomości',
        'položky',
        'správy',
        'письма',
        'письмо',
        'элементы',
        'сообщения',
        'пошта',
        // Other
        'öğeler',
        'mesajlar',
        'μηνύματα',
        'στοιχεία'
    ].map(token => token.toLowerCase().normalize('NFKC'))
);

// Word separators seen in folder names across clients.
const TOKEN_SPLIT = /[\s\-_/.,()[\]]+/;

// Localized folder name mappings for detecting special-use mailboxes.
// When the server does not advertise the SPECIAL-USE extension (RFC 6154),
// we fall back to matching folder names against these lists of known
// translations in various languages (including non-Latin scripts).
module.exports = {
    flags: ['\\All', '\\Archive', '\\Drafts', '\\Flagged', '\\Junk', '\\Sent', '\\Trash'],
    names: {
        '\\Sent': [
            'aika',
            'bidaliak',
            'bidalita',
            'dihantar',
            'e rometsweng',
            'e tindami',
            'elküldött',
            'elküldöttek',
            'elementos enviados',
            'éléments envoyés',
            'enviadas',
            'enviados',
            'enviats',
            'envoyés',
            'ethunyelweyo',
            'expediate',
            'ezipuru',
            'gesendete',
            'gesendete elemente',
            'gestuur',
            'gönderilmiş öğeler',
            'göndərilənlər',
            'iberilen',
            'inviati',
            'išsiųstieji',
            'kuthunyelwe',
            'lasa',
            'lähetetyt',
            'messages envoyés',
            'naipadala',
            'nalefa',
            'napadala',
            'nosūtītās ziņas',
            'odeslané',
            'odeslaná pošta',
            'padala',
            'poslane',
            'poslano',
            'poslané',
            'poslato',
            'saadetud',
            'saadetud kirjad',
            'saadetud üksused',
            'sendt',
            'sent',
            'sent items',
            'sent messages',
            'sända poster',
            'sänt',
            'terkirim',
            'ti fi ranṣẹ',
            'të dërguara',
            'verzonden',
            'vilivyotumwa',
            'wysłane',
            'đã gửi',
            'σταλθέντα',
            'жиберилген',
            'жіберілгендер',
            'изпратени',
            'илгээсэн',
            'ирсол шуд',
            'испратено',
            'надіслані',
            'отправленные',
            'пасланыя',
            'юборилган',
            'ուղարկված',
            'נשלחו',
            'פריטים שנשלחו',
            'المرسلة',
            'بھیجے گئے',
            'سوزمژہ',
            'لېګل شوی',
            'موارد ارسال شده',
            'पाठविले',
            'पाठविलेले',
            'प्रेषित',
            'भेजा गया',
            'প্রেরিত',
            'প্ৰেৰিত',
            'ਭੇਜੇ',
            'મોકલેલા',
            'ପଠାଗଲା',
            'அனுப்பியவை',
            'పంపించబడింది',
            'ಕಳುಹಿಸಲಾದ',
            'അയച്ചു',
            'යැවු පණිවුඩ',
            'ส่งแล้ว',
            'გაგზავნილი',
            'የተላኩ',
            'បាន​ផ្ញើ',
            '寄件備份',
            '已发信息',
            '送信済みメール',
            '발신 메시지',
            '보낸 편지함'
        ],
        '\\Trash': [
            'articole șterse',
            'bin',
            'borttagna objekt',
            'cestino',
            'corbeille',
            'coș de gunoi',
            'deleted',
            'deleted items',
            'deleted messages',
            'dzēstie vienumi',
            'elementi eliminati',
            'elementos borrados',
            'elementos eliminados',
            'elements suprimits',
            'gelöschte elemente',
            'gelöschte objekte',
            'item dipadam',
            'itens apagados',
            'itens excluídos',
            'ištrinti',
            'kosz',
            'koš',
            'kuka',
            'kustutatud üksused',
            'kôš',
            'lixeira',
            'lixo',
            'mục đã xóa',
            'obrisane stavke',
            'odstraněná pošta',
            'odstraněné položky',
            'papelera',
            'papierkorb',
            'papirkurv',
            'papperskorg',
            'papperskorgen',
            'pesan terhapus',
            'poistetut',
            'praht',
            'prullenbak',
            'prügikast',
            'roskakori',
            'rusl',
            'silinmiş öğeler',
            'slettede beskeder',
            'slettede elementer',
            'smeće',
            'thùng rác',
            'trash',
            'törölt',
            'törölt elemek',
            'usunięte wiadomości',
            'verwijderde items',
            'vymazané správy',
            'çöp',
            'çöp kutusu',
            'éléments supprimés',
            'διαγραμμένα',
            'κάδος απορριμμάτων',
            'видалені',
            'выдаленыя',
            'жойылғандар',
            'избришани',
            'изтрити',
            'корзина',
            'кошик',
            'кошче',
            'обрисане ставке',
            'сметніца',
            'удаленные',
            'удалённые',
            'אשפה',
            'פריטים שנמחקו',
            'العناصر المحذوفة',
            'المهملات',
            'موارد حذف شده',
            'ถังขยะ',
            'รายการที่ลบ',
            'ゴミ箱',
            '削除済みアイテム',
            '垃圾桶',
            '已删除邮件',
            '已刪除項目',
            '지운 편지함',
            '휴지통'
        ],
        '\\Junk': [
            'bulk mail',
            'correo lixo',
            'correo no deseado',
            'correu brossa',
            'courrier indésirable',
            'gemorspos',
            'istenmeyen',
            'istenmeyen e-posta',
            'junk',
            'junk e-mail',
            'junk email',
            'junk mail',
            'junk-e-mail',
            'levélszemét',
            'lixo electrónico',
            'lixo eletrônico',
            'mesaje nedorite',
            'mēstules',
            'nevyžiadaná pošta',
            'nevyžádaná pošta',
            'neželena pošta',
            'neželjena pošta',
            'no deseado',
            'ongewenste e-mail',
            'posta indesiderata',
            'pourriel',
            'roskaposti',
            'ruslpóstur',
            'rämpspost',
            'skräppost',
            'spam',
            'spamowanie',
            'søppelpost',
            'thư rác',
            'uønsket e-mail',
            'uønsket e-post',
            'uønsket post',
            'wiadomości-śmieci',
            'zabor-posta',
            'šlamštas',
            'ανεπιθύμητη αλληλογραφία',
            'небажана пошта',
            'нежелана поща',
            'нежелательная почта',
            'непажаданая пошта',
            'непожељна пошта',
            'непосакувана пошта',
            'спам',
            'қалаусыз пошта',
            'սպամ',
            'דואר זבל',
            'الرسائل العشوائية',
            'هرزنامه',
            'स्पैम',
            'สแปม',
            'อีเมลขยะ',
            'სპამი',
            '垃圾邮件',
            '垃圾郵件',
            '垃圾電郵',
            '迷惑メール',
            '스팸',
            '정크 메일'
        ],
        '\\Drafts': [
            'ba brouillon',
            'borrador',
            'borradores',
            'bozze',
            'brouillons',
            'bản thảo',
            'ciorne',
            'concepten',
            'draf',
            'draft',
            'drafts',
            'drög',
            'entwürfe',
            'esborranys',
            'garalamalar',
            'ihe edeturu',
            'iidrafti',
            'izinhlaka',
            'juodraščiai',
            'kladd',
            'kladder',
            'koncepty',
            'konsep',
            'konsepte',
            'kopie robocze',
            'layihələr',
            'luonnokset',
            'melnraksti',
            'meralo',
            'mesazhe të padërguara',
            'mga draft',
            'mustandid',
            'nacrti',
            'osnutki',
            'piszkozatok',
            'rascunhos',
            'rasimu',
            'skice',
            'taslaklar',
            'tsararrun saƙonni',
            'utkast',
            'vakiraoka',
            'vázlatok',
            'zirriborroak',
            'àwọn àkọpamọ́',
            'πρόχειρα',
            'жобалар',
            'нацрти',
            'нооргууд',
            'сиёҳнавис',
            'хомаки хатлар',
            'чарнавікі',
            'чернетки',
            'чернови',
            'черновики',
            'черновиктер',
            'սեւագրեր',
            'טיוטות',
            'مسودات',
            'موسودې',
            'پیش نویسها',
            'ڈرافٹ/',
            'ड्राफ़्ट',
            'प्रारूप',
            'খসড়া',
            'ড্ৰাফ্ট',
            'ਡ੍ਰਾਫਟ',
            'ડ્રાફ્ટસ',
            'ଡ୍ରାଫ୍ଟ',
            'வரைவுகள்',
            'చిత్తు ప్రతులు',
            'ಕರಡುಗಳು',
            'കരടുകള്‍',
            'කෙටුම් පත්',
            'ฉบับร่าง',
            'მონახაზები',
            'ረቂቆች',
            'សារព្រាង',
            '下書き',
            '草稿',
            '임시 보관함'
        ],

        '\\Archive': [
            'archief',
            'archiv',
            'archive',
            'archives',
            'archivio',
            'archivo',
            'archiwum',
            'archyvas',
            'archív',
            'archívum',
            'argief',
            'arhiiv',
            'arhiv',
            'arhiva',
            'arhivă',
            'arhīvs',
            'arkib',
            'arkisto',
            'arkiv',
            'arquivo',
            'arsip',
            'artxiboa',
            'arxiu',
            'arxiv',
            'arşiv',
            'lưu trữ',
            'αρχειοθήκη',
            'архив',
            'архива',
            'архів',
            'архіў',
            'мұрағат',
            'արխիվ',
            'ארכיון',
            'أرشيف',
            'الأرشيف',
            'بایگانی',
            'संग्रह',
            'ที่เก็บถาวร',
            'არქივი',
            'アーカイブ',
            '存档',
            '存檔',
            '封存',
            '보관 편지함',
            '보관함'
        ]
    }
};

// Exact lookup index over the tables above, built once at module load. `names` is
// treated as read-only from here on; nothing in the library mutates it after this point.
const NAME_INDEX = new Map();
for (let flag of Object.keys(module.exports.names)) {
    for (let entry of module.exports.names[flag]) {
        NAME_INDEX.set(entry, flag);
    }
}

// Fold a folder name into the form the name tables are stored in.
// Remove U+200E (LEFT-TO-RIGHT MARK) which some mail clients (especially for
// RTL languages like Arabic, Hebrew) insert into folder names for display purposes.
// These invisible marks would otherwise prevent exact string matching.
// Normalize with NFKC last: the same folder name can arrive in different but
// equivalent forms depending on the client that created it, and matching is exact.
// NFKC rather than NFC because the compatibility folding is what maps halfwidth
// katakana and fullwidth Latin onto the regular forms that servers actually send.
// Every entry in the tables above is stored in NFKC form, which a test asserts.
function normalizeName(name) {
    return name
        .toLowerCase()
        .replace(/\u200e/g, '')
        .trim()
        .normalize('NFKC');
}

module.exports.specialUse = (hasSpecialUseExtension, folder) => {
    // If the server supports SPECIAL-USE (RFC 6154), check for special-use flags first.
    // Extension-provided flags take precedence over name-based detection because they
    // are authoritative -- the server explicitly marks the folder's role.
    if (hasSpecialUseExtension) {
        const flag = module.exports.flags.find(flag => folder.flags.has(flag));
        if (flag) {
            return { flag, source: 'extension' };
        }
    }

    let name = normalizeName(folder.name);

    // Fallback 1: the name is exactly a known localized folder name.
    let flag = NAME_INDEX.get(name);
    if (flag) {
        return { flag, source: 'name' };
    }

    // Fallback 2: the name is a known folder name decorated with generic mail nouns
    // ("Sent Mail", "Otpravlennye pisma"). Stripping them has to leave exactly one word,
    // and that word still has to be a known name - this tier never matches approximately.
    // Reported as a separate, lower priority source because the decoration makes it a
    // weaker signal than an exactly named folder.
    let core = name.split(TOKEN_SPLIT).filter(token => token && !GENERIC_TOKENS.has(token));
    if (core.length === 1 && core[0] !== name) {
        flag = NAME_INDEX.get(core[0]);
        if (flag) {
            return { flag, source: 'name-guess' };
        }
    }

    return { flag: null };
};
