'use strict';

// Generic mail nouns that decorate a special-use folder name without changing what
// it means: "Sent Mail", "Gelöschte Elemente", "Отправленные письма". Stripping them
// lets a decorated name fall back to its core word. A name that still has more than
// one meaningful word left after stripping is treated as a user folder and rejected,
// which is what separates "Sent Mail" (a real Sent folder) from "Sent to clients".
// Words that name a special-use folder on their own (like "bin") do not belong here,
// and neither do hyphenated words, since TOKEN_SPLIT below splits on the hyphen and
// no such token could ever be produced.
// Folded by construction so the set matches the form tokens are compared against,
// the same invariant the name tables are tested for.
const GENERIC_TOKENS = new Set(
    [
        // English. "e" is here because TOKEN_SPLIT breaks on the hyphen, so the
        // "e-mail" / "e-posta" / "e-kirjad" family arrives as a bare "e" token.
        'e',
        'mail',
        'mails',
        'email',
        'emails',
        'message',
        'messages',
        'item',
        'items',
        'folder',
        'my',
        // German, Dutch, Nordic
        'objekt',
        'objekte',
        'objekten',
        'objekter',
        'elemente',
        'elementen',
        'elementer',
        'nachrichten',
        'berichten',
        'post',
        'poster',
        'viestit',
        'kirjad',
        'meldinger',
        'beskeder',
        // Romance
        'correo',
        'posta',
        'courrier',
        'elementos',
        'elementi',
        'éléments',
        'mensajes',
        'messaggi',
        'mensagens',
        'itens',
        // Slavic
        'poczta',
        'pošta',
        'elementy',
        'wiadomości',
        'položky',
        'správy',
        'письма',
        'письмо',
        'элементы',
        'сообщения',
        'пошта',
        // Other
        'öğeler',
        'mesajlar',
        'μηνύματα',
        'στοιχεία'
    ].map(token => token.toLowerCase().normalize('NFKC'))
);

// Word separators seen in folder names across clients.
const TOKEN_SPLIT = /[\s\-_/.,()[\]]+/;

// Localized folder name mappings for detecting special-use mailboxes.
// When the server does not advertise the SPECIAL-USE extension (RFC 6154),
// we fall back to matching folder names against these lists of known
// translations in various languages (including non-Latin scripts).
module.exports = {
    flags: ['\\All', '\\Archive', '\\Drafts', '\\Flagged', '\\Junk', '\\Sent', '\\Trash'],
    names: {
        '\\Sent': [
            'aika',
            'air a chur',
            'am post cuirte',
            'anfonwyd',
            'bidalia',
            'bidaliak',
            'bidalita',
            'bidalitakoak',
            'currieru mandatu',
            'danfonwyd',
            'dihantar',
            'e rometsweng',
            'e tindami',
            'elementos enviados',
            'elküldött',
            'elküldött elemek',
            'elküldött üzenetek',
            'elküldöttek',
            'enviadas',
            'enviados',
            'enviat',
            'enviats',
            'envoyés',
            'ethunyelweyo',
            'expediate',
            'ezipuru',
            'ferstjoerd',
            'gesendet',
            'gesendete',
            'gesendete elemente',
            'gestuur',
            'gönderilmiş',
            'gönderilmiş öğeler',
            'göndərilənlər',
            'hantar',
            'iberilen',
            'inviata',
            'inviate',
            'inviati',
            'išsiųsti',
            'išsiųsti laiškai',
            'išsiųstieji',
            'jo`natilgan xatlar',
            'jo‘natilgan',
            'kaset',
            'kuthunyelwe',
            'küldöttek',
            'lasa',
            'lähetetyt',
            'mesaje trimise',
            'messages envoyés',
            'naipadala',
            'nalefa',
            'napadala',
            'nosūtīts',
            'nosūtītās',
            'nosūtītās ziņas',
            'odeslaná pošta',
            'odeslané',
            'odoslaná',
            'odoslaná pošta',
            'odoslané',
            'padala',
            'poslana pošta',
            'poslane',
            'poslano',
            'poslané',
            'poslato',
            'posta inviata',
            'pósłane',
            'pósłany',
            'saadetud',
            'saadetud kirjad',
            'saadetud üksused',
            'senditujo',
            'sendt',
            'sendt post',
            'sendte',
            'sendte beskeder',
            'sent',
            'sent items',
            'sent messages',
            'seolta',
            'siūsti',
            'skickat',
            'sända poster',
            'sänt',
            'sūtīt',
            'terkirim',
            'thư đã gửi',
            'ti fi ranṣẹ',
            'titaq',
            'tramess',
            'trimis',
            'trimise',
            'ttwaznen',
            'të dërguar',
            'të dërguara',
            'unviaos',
            'unvios fechos',
            'verschéckt',
            'verzonden',
            'verzonden berichten',
            'vilivyotumwa',
            'wysłane',
            'éléments envoyés',
            'đã gửi',
            'şandî',
            'απεσταλμένα',
            'σταλθέντα',
            'адпраўлена',
            'жиберилген',
            'жіберілген',
            'жіберілген хаттар',
            'жіберілгендер',
            'изпратени',
            'изпратени писма',
            'илгээсэн',
            'ирсол шуд',
            'испратени',
            'испратено',
            'надіслані',
            'отправленные',
            'пасланыя',
            'послате',
            'послато',
            'пратени',
            'юборилган',
            'ուղարկուած',
            'ուղարկված',
            'נשלח',
            'נשלחו',
            'פריטים שנשלחו',
            'ئەۋەتىلگەن',
            'ارسال شده',
            'ارسالی',
            'البريد المرسل',
            'المرسل',
            'المرسلة',
            'المُرسَل',
            'بھیجا ہوا میل',
            'بھیجے گئے',
            'سوزمژہ',
            'لېږل شوي ليکونه',
            'لېګل شوی',
            'موارد ارسال شده',
            'مُرسَل',
            'نێردراو',
            'पठईएका मेलहरु',
            'पाठवलेले',
            'पाठविले',
            'पाठविलेले',
            'प्रेषित',
            'भेजा गया',
            'भेजे गए',
            'পাঠানো হয়েছে',
            'প্রেরিত',
            'প্রেরিত(পাঠানো মেইল)',
            'প্ৰেৰিত',
            'ਭੇਜੇ',
            'મોકલેલા',
            'મોકલેલ્યા',
            'ପଠାଗଲା',
            'அனுப்பிய அஞ்சல்',
            'அனுப்பியவை',
            'పంపించబడింది',
            'ಕಳುಹಿಸಲಾದ',
            'അയച്ചവ',
            'അയച്ചു',
            'යැවු පණිවුඩ',
            'යැවූ',
            'ที่ส่งแล้ว',
            'ส่ง',
            'ส่งแล้ว',
            'გაგზავნილი',
            'ዝተለኣኸ',
            'የተላኩ',
            'បាន​ផ្ញើ',
            'សំបុត្រដែលបានបញ្ជូន',
            '寄件備份',
            '已发信息',
            '已发送',
            '已发送消息',
            '已发送邮件',
            '送信済み',
            '送信済みアイテム',
            '送信済みトレイ',
            '送信済みメール',
            '발신 메시지',
            '보낸 편지함',
            '보냄'
        ],
        '\\Trash': [
            'an sgudal',
            'articole șterse',
            'atkritne',
            'bin',
            'borttaget',
            'borttagna objekt',
            'bosca bruscair',
            'bruscar',
            'cestino',
            'chanaster da palpiri',
            'chiqitdon',
            'corbe a papiro',
            'corbeille',
            'coș de gunoi',
            'curbella',
            'deleted',
            'deleted items',
            'deleted messages',
            'dzēstie vienumi',
            'elementi eliminati',
            'elementos borrados',
            'elementos eliminados',
            'elements suprimits',
            'eliminata',
            'gelöscht',
            'gelöschte elemente',
            'gelöschte objekte',
            'gunoi',
            'hedhurina',
            'item dipadam',
            'itens apagados',
            'itens eliminados',
            'itens excluídos',
            'ištrinti',
            'iḍuman',
            'jiskefet',
            'jêbirdank',
            'kanta',
            'kest',
            'kosz',
            'koš',
            'kuka',
            'kustutatud',
            'kustutatud üksused',
            'kôš',
            'lixeira',
            'lixo',
            'lomtár',
            'molwuj',
            'mục đã xóa',
            'obrisane stavke',
            'odpadkový kôš',
            'odstraněná pošta',
            'odstraněné položky',
            'papeleira',
            'papelera',
            'paperera',
            'papierkorb',
            'papirkorg',
            'papirkurv',
            'papjernik',
            'papperskorg',
            'papperskorgen',
            'papīrgrozs',
            'papīrkurvis',
            'pesan terhapus',
            'pod-lastez',
            'poistetut',
            'poubelle',
            'praht',
            'prullenbak',
            'prügikast',
            'reciclagem',
            'roskakori',
            'rubujo',
            'rusl',
            'savat',
            'sbwriel',
            'sgudal',
            'silinmiş öğeler',
            'skrell',
            'sletta',
            'slettede beskeder',
            'slettede elementer',
            'slettet',
            'smeti',
            'smeće',
            'snippermandjie',
            'surat terhapus',
            'səbət',
            'thùng rác',
            'tong sampah',
            'trash',
            'törölt',
            'törölt elemek',
            'usunięte',
            'usunięte wiadomości',
            'verwijderde items',
            'vymazané správy',
            'zakarrontzia',
            'çöp',
            'çöp kutusu',
            'éléments supprimés',
            'šiukšliadėžė',
            'šiukšlinė',
            'šiukšlių dėžė',
            'șterse',
            'απορρίμματα',
            'διαγραμμένα',
            'κάδος απορριμάτων',
            'κάδος απορριμμάτων',
            'видалені',
            'выдаленыя',
            'жойылғандар',
            'избришани',
            'изтрити',
            'канта',
            'корзина',
            'корпа',
            'кошик',
            'кошче',
            'обрисане ставке',
            'себет',
            'сметніца',
            'смеће',
            'смітник',
            'удаленные',
            'удалённые',
            'хогийн сав',
            'қоқыс шелегі',
            'աղբարկղ',
            'אשפה',
            'פריטים שנמחקו',
            'اشغال دانی',
            'العناصر المحذوفة',
            'المهملات',
            'ردی کی ٹوکری',
            'زباله‌دان',
            'زبڵدان',
            'موارد حذف شده',
            'مُهملات',
            'کثافت دانۍ',
            'कचरा',
            'कचरा पेटी',
            'रद्दी',
            'रद्दी टोकरी',
            'ঝুড়ি',
            'ডাস্টবিন',
            'કચરો',
            'குப்பை',
            'ചവറ്റുകുട്ട',
            'ඉවතලන බඳුන',
            'ถังขยะ',
            'รายการที่ลบ',
            'ნაგავი',
            'ურნა',
            'წაშლილი',
            'እንዳጉሓፍ',
            'ធុងសំរាម',
            'ごみ箱',
            'ゴミ箱',
            '削除済みアイテム',
            '回收站',
            '垃圾桶',
            '已删除邮件',
            '已刪除項目',
            '废件箱',
            '지운 편지함',
            '휴지통'
        ],
        '\\Junk': [
            'aspam',
            'basura',
            'brukalas',
            'bulk mail',
            'cajk',
            'correo basura',
            'correo lixo',
            'correo no deseado',
            'correu brossa',
            'corréu puxarra',
            'courrier indésirable',
            'dramhaíl',
            'dramhphost',
            'gemors',
            'gemorspos',
            'gereksiz',
            'indesiderata',
            'indesirate',
            'indésirables',
            'istenmeyen',
            'istenmeyen e-posta',
            'i̇stenmeyen',
            'junk',
            'junk e-mail',
            'junk email',
            'junk mail',
            'junk-e-mail',
            'kéretlen',
            'lastez',
            'levélszemét',
            'lixo electrónico',
            'lixo eletrónico',
            'lixo eletrônico',
            'mel remeh',
            'mesaje nedorite',
            'møsn',
            'mēstule',
            'mēstules',
            'nepoželjne',
            'nesolicitate',
            'net-winske',
            'nevyžiadaná pošta',
            'nevyžádaná',
            'nevyžádaná pošta',
            'nevēlams',
            'nezaželeno',
            'neželena pošta',
            'neželena sporočila',
            'neželjena pošta',
            'niechciane',
            'no deseado',
            'nungiavischà',
            'ongewenst',
            'ongewenste e-mail',
            'posta indesiderata',
            'posta indesirate',
            'pourriel',
            'pourriels',
            'puxarra',
            'roskaa',
            'roskaposti',
            'roskapostit',
            'ruslpóstur',
            'rämps',
            'rämpspost',
            'sbam',
            "seq'",
            'skräp',
            'skräppost',
            'sothach',
            'spam',
            'spamowanie',
            'spamujo',
            'stroboù',
            'szemét',
            'søppelpost',
            'thư rác',
            'truilleis',
            'të pavlera',
            'të pavlerë',
            'uønsket',
            'uønsket e-mail',
            'uønsket e-post',
            'uønsket post',
            'uønskt',
            'wiadomości-śmieci',
            'zabor-posta',
            'zaborra',
            'önemsiz',
            'čapor',
            'šiukšlės',
            'šlamštas',
            'ανεπιθύμητα',
            'ανεπιθύμητη αλληλογραφία',
            'небажана пошта',
            'нежелана поща',
            'нежелательная почта',
            'непажаданая пошта',
            'непожељна пошта',
            'непожељне',
            'непожељно',
            'непосакувана пошта',
            'спам',
            'қалаусыз пошта',
            'անպիտան',
            'թափոն',
            'սպամ',
            'דואר זבל',
            'זבל',
            'الرسائل العشوائية',
            'الرسائل غير المرغوب فيها',
            'بنجل',
            'بیکاره',
            'بێکه‌ڵک',
            'جنک',
            'جنک میل',
            'سُخام',
            'غير المرغوب',
            'هرزنامه',
            'नको असलेले कचरा संदेश',
            'स्पाम',
            'स्पैम',
            'আজেবাজে মেইল',
            'எரிதம்',
            'ആവശ്യമില്ലാത്തവ',
            'සුන්බුන්',
            'กล่องจดหมายขยะ',
            'ขยะ',
            'สแปม',
            'อีเมลขยะ',
            'სპამი',
            'ჯართი',
            'እንዳቅንጠመንጢ',
            'សំបុត្រមិនល្អ',
            'ឥត​បាន​ការ',
            '垃圾',
            '垃圾信件',
            '垃圾邮件',
            '垃圾郵件',
            '垃圾電郵',
            '迷惑メール',
            '스팸',
            '스팸 편지함',
            '정크',
            '정크 메일'
        ],
        '\\Drafts': [
            'arewway',
            'ba brouillon',
            'borrador',
            'borradores',
            'bozze',
            'brouilhedoù',
            'brouillonen',
            'brouillons',
            'bruttacopie',
            'bản thảo',
            'ciorne',
            'concepten',
            'draf',
            'drafftiau',
            'draft',
            'drafts',
            'dreachdan',
            'dréachtaí',
            'drög',
            'entwürfe',
            'esborranys',
            'esbossos',
            'garalamalar',
            'ihe edeturu',
            'iidrafti',
            'izinhlaka',
            'juodraščiai',
            'jusamaj',
            'kladd',
            'kladdar',
            'kladder',
            'koncepty',
            'konsep',
            'konsepte',
            'konsepten',
            'kopie robocze',
            'layihələr',
            'luonnokset',
            'malnetujo',
            'melnraksti',
            'meralo',
            'mesaje nefinalizate',
            'mesazhe të padërguara',
            'mga draft',
            'mustandid',
            'nacerjenja',
            'nacrti',
            'naćiski',
            'nedovršene',
            'nedovršeno',
            'onvoltooid',
            'osnutki',
            'piszkozatok',
            'qaralamalar',
            'qoralama xatlar',
            'qoralamalar',
            'rascunhos',
            'rasimu',
            'reşnivîs',
            'rozepsané',
            'sbozs',
            'skica',
            'skice',
            'skitsur',
            'szkice',
            'taslak',
            'taslaklar',
            'thư nháp',
            'tsararrun saƙonni',
            'utkast',
            'uzmetumi',
            'vakiraoka',
            'versiones provisori',
            'vázlatok',
            'wersje robocze',
            'zirriborroak',
            'àwọn àkọpamọ́',
            'προσχέδια',
            'πρόχειρα',
            'драфтови',
            'жоба жазбалар',
            'жобалар',
            'нацрти',
            'недовршене',
            'недовршено',
            'непратени',
            'нооргууд',
            'ноорог',
            'сиёҳнавис',
            'скици',
            'хомаки хатлар',
            'чарнавікі',
            'чернетки',
            'чернови',
            'черновики',
            'черновиктер',
            'шимай қағаз',
            'սեւագրեր',
            'טיוטות',
            'المسودات',
            'بارليک',
            'قوليازمىلار',
            'مسودات',
            'مسوّدات',
            'موسودې',
            'نامه های ناتکمیل',
            'پیش نویسها',
            'پیش‌نویس‌ها',
            'ڈرافٹ',
            'ڈرافٹ/',
            'ڕه‌شنووسەکان',
            'ड्राफ़ट',
            'ड्राफ़्ट',
            'ड्राफ्ट',
            'ड्राफ्टहरू',
            'प्रारूप',
            'मसुदा',
            'খসড়া',
            'ড্ৰাফ্ট',
            'ਡ੍ਰਾਫਟ',
            'ડ્રાફ્ટ',
            'ડ્રાફ્ટસ',
            'ଡ୍ରାଫ୍ଟ',
            'வரைவுகள்',
            'చిత్తు ప్రతులు',
            'ಕರಡುಗಳು',
            'കരടുകള്‍',
            'ഡ്രാഫ്റ്റുകൾ',
            'പൂര്‍ത്തിയാകാത്തവ',
            'කටු සටහන්',
            'කෙටුම් පත්',
            'กล่องจดหมายร่าง',
            'ฉบับร่าง',
            'ร่าง',
            'လိက်အပြောံ',
            'დროებითი',
            'მონახაზები',
            'წინასწარი',
            'ረቂቆች',
            'ወጡን ጽሑፍ',
            'សារព្រាង',
            'សេចក្ដី​ព្រាង​',
            'សំបុត្រពង្រៀង',
            '下書き',
            '草稿',
            '草稿匣',
            '草稿箱',
            '임시 보관함',
            '초안'
        ],

        '\\Archive': [
            'an chartlann',
            'archief',
            'archieven',
            'archif',
            'archifau',
            'archiv',
            'archivados',
            'archivar',
            'archive',
            'archives',
            'archivi',
            'archivio',
            'archivo',
            'archivos',
            'archivovať',
            'archivs',
            'archivu',
            'archiválás',
            'archiwum',
            'archiwy',
            'archyvas',
            'archyvuoti',
            'archív',
            'archívum',
            'archívy',
            'argief',
            'argiven',
            'argyf',
            'arhiiv',
            'arhiv',
            'arhiva',
            'arhive',
            'arhivi',
            'arhivă',
            'arhīvi',
            'arhīvs',
            'arkib',
            'arkisto',
            'arkiv',
            'arkiva',
            'arkiver',
            'arkivo',
            'arkivoje',
            'arquivamento',
            'arquivo',
            'arquivo morto',
            'arquivos',
            'arsip',
            'artxibatu',
            'artxiboa',
            'artxiboak',
            'arxiu',
            'arxiv',
            'arxivlar',
            'arşiv',
            'arşivler',
            'aḥraz',
            'cartlanna',
            'diell',
            'dielloù',
            'erşîv',
            'geymsla',
            'goym í skjalasavni',
            'iɣbaren',
            'lưu trữ',
            'skjalageymsla',
            "taq yakb'äl",
            'tasg-lannan',
            'αρχειοθέτηση',
            'αρχειοθήκη',
            'архив',
            'архива',
            'архиве',
            'архиви',
            'архивирай',
            'архивтер',
            'архивы',
            'архів',
            'архіви',
            'архівы',
            'архіў',
            'мұрағат',
            'արխիվ',
            'արխիւներ',
            'ארכיון',
            'أرشفة',
            'أرشيف',
            'ئارخىپ',
            'ئەرشیف',
            'ارشیو',
            'الأرشيف',
            'بایگانی',
            'जतन केलेला',
            'संग्रह',
            'ശേഖരം',
            'සංරක්‍ෂණය',
            'การเก็บถาวร',
            'ที่เก็บถาวร',
            'არქივები',
            'არქივი',
            'ប័ណ្ណសារ',
            'ប័ណ្ណសារ​',
            'アーカイブ',
            '備存',
            '存档',
            '存檔',
            '封存',
            '归档',
            '보관 편지함',
            '보관함',
            '저장 편지함'
        ]
    }
};

// Exact lookup index over the tables above, built once at module load. `names` is
// treated as read-only from here on; nothing in the library mutates it after this point.
const NAME_INDEX = new Map();
for (let flag of Object.keys(module.exports.names)) {
    for (let entry of module.exports.names[flag]) {
        NAME_INDEX.set(entry, flag);
    }
}

// Fold a folder name into the form the name tables are stored in.
// Remove U+200E (LEFT-TO-RIGHT MARK) which some mail clients (especially for
// RTL languages like Arabic, Hebrew) insert into folder names for display purposes.
// These invisible marks would otherwise prevent exact string matching.
// Normalize with NFKC last: the same folder name can arrive in different but
// equivalent forms depending on the client that created it, and matching is exact.
// NFKC rather than NFC because the compatibility folding is what maps halfwidth
// katakana and fullwidth Latin onto the regular forms that servers actually send.
// Every entry in the tables above is stored in NFKC form, which a test asserts.
function normalizeName(name) {
    return name
        .toLowerCase()
        .replace(/\u200e/g, '')
        .trim()
        .normalize('NFKC');
}

module.exports.specialUse = (hasSpecialUseExtension, folder) => {
    // If the server supports SPECIAL-USE (RFC 6154), check for special-use flags first.
    // Extension-provided flags take precedence over name-based detection because they
    // are authoritative -- the server explicitly marks the folder's role.
    if (hasSpecialUseExtension) {
        const flag = module.exports.flags.find(flag => folder.flags.has(flag));
        if (flag) {
            return { flag, source: 'extension' };
        }
    }

    let name = normalizeName(folder.name);

    // Fallback 1: the name is exactly a known localized folder name.
    let flag = NAME_INDEX.get(name);
    if (flag) {
        return { flag, source: 'name' };
    }

    // Fallback 2: the name is a known folder name decorated with generic mail nouns
    // ("Sent Mail", "Otpravlennye pisma"). Stripping them has to leave exactly one word,
    // and that word still has to be a known name - this tier never matches approximately.
    // Reported as a separate, lower priority source because the decoration makes it a
    // weaker signal than an exactly named folder.
    let core = name.split(TOKEN_SPLIT).filter(token => token && !GENERIC_TOKENS.has(token));
    if (core.length === 1 && core[0] !== name) {
        flag = NAME_INDEX.get(core[0]);
        if (flag) {
            return { flag, source: 'name-guess' };
        }
    }

    return { flag: null };
};
